<?= view('v2/template/homepage_template_v2', [
    // navbar & link
    'homepage_link' => '/',
    'homepage_link_title' => 'Beranda',
    'product_link' => '/product',
    'product_link_title' => 'Produk',
    'about_us_link' => '/about-us',
    'about_us_link_title' => 'Tentang Kami',
    'about_us_2_link_title' => 'Tentang',
    'contact_us_link' => '/contact-us',
    'contact_us_link_title' => 'Hubungi Kami',
    'contact_us_2_link_title' => 'Kontak',
    'gallery_link' => '/galeri',
    'gallery_link_title' => 'Galeri',

    // content
    'hero_title' => 'Solusi Pengadaan Terpercaya Beragam Kebutuhan Anda',
    'overview_top_title' => 'Menghadirkan Nilai,',
    'overview_bottom_title' => 'Bukan Sekadar Barang',
    'overview_description' => 'Kami tidak hanya menyediakan produk, tapi solusi bernilai bagi instansi dan bisnis. Dengan layanan
                        terpercaya, kami mendukung efisiensi, kualitas, dan keberlanjutan dalam setiap pengadaan untuk
                        kemajuan operasional, layanan publik, dan pembangunan jangka panjang.',
    'order_title' => 'Permintaan Terpenuhi',
    'cities_title' => 'Kota Dijangkau',
    'total_product_title' => 'Total Produk',
    'claim_description' => 'Dipercaya oleh berbagai instansi di seluruh Indonesia, kami terus tumbuh dan berkembang untuk memenuhi kebutuhan Anda.',
    'see_product_button' => 'Lihat Produk',
    'service_top_title' => 'Kami Memberikan',
    'service_bottom_title' => 'Yang Terbaik',
    'service_bottom_title_2' => 'Yang Terbaik Untuk Anda',
    'service_1_title' => 'Pembayaran & Garansi',
    'service_1_description' => 'Nikmati kemudahan pembayaran dengan pilihan bank apapun serta garansi produk untuk kenyamanan Anda.',
    'service_2_title' => 'Harga, Stok, & Pengiriman',
    'service_2_description' => 'Kami menawarkan harga yang lebih murah dari distributor lain, stok selalu tersedia, dan pengiriman fleksibel sesuai kebutuhan Anda.',
    'service_3_title' => 'Layanan Khusus & Konsultasi',
    'service_3_description' => 'Kami menyediakan layanan konsultasi produk, custom merk, gratis sampel untuk produk tertentu.',
    'service_description' => 'Pengadaan perlengkapan outdoor hingga infrastruktur dengan layanan cepat, terpercaya, dan dukungan profesional.',
    'preparation_top_title' => 'Dari Desan',
    'preparation_bottom_title' => 'Hingga Pengiriman',
    'preparation_1_title' => 'Perencanaan & Desain',
    'preparation_1_description' => 'Kami mulai dengan perencanaan matang dan desain produk sesuai kebutuhan pelanggan.',
    'preparation_2_title' => 'Produksi & Pengolahan',
    'preparation_2_description' => 'Kami mulai dengan perencanaan matang dan desain produk sesuai kebutuhan pelanggan.',
    'preparation_3_title' => 'Kontrol Kualitas',
    'preparation_3_description' => 'Setiap produk melewati pemeriksaan ketat untuk memastikan kualitas terbaik.',
    'preparation_4_title' => 'Pengiriman & Distribusi',
    'preparation_4_description' => 'Produk dikirim tepat waktu dengan layanan pengiriman yang handal dan aman.',
    'why_us_top_title' => 'Mengapa',
    'why_us_bottom_title' => 'Memilih Kami',
    'why_us_1_title' => 'Kustom Merk',
    'why_us_1_description' => 'Memungkinkan produk disesuaikan dengan logo dan identitas bisnis Anda.',
    'why_us_2_title' => 'Harga Kompetitif',
    'why_us_2_description' => 'Kami menawarkan harga terbaik yang bersaing di pasar.',
    'why_us_3_title' => 'Kualitas Terjamin',
    'why_us_3_description' => 'Produk kami melewati kontrol kualitas ketat untuk kepuasan Anda.',
    'why_us_4_title' => 'Layanan Profesional',
    'why_us_4_description' => 'Tim kami siap membantu dan memberikan konsultasi terbaik.',
    'why_us_description' => 'Kami selalu mengutamakan kualitas produk dan pelayanan untuk memastikan setiap pelanggan mendapatkan solusi terbaik. Integritas dan kepercayaan menjadi landasan utama dalam setiap langkah kami.',
    'about_us_top_title' => 'Sekilas',
    'about_us_bottom_title' => 'Tentang Kami',
    'about_us_description' => 'PT. Karya Pilar Nusantara adalah perusahaan terpercaya yang berfokus pada pengadaan berbagai kebutuhan instansi dan dunia usaha. Kami berkomitmmen memberikan produk berkualitas, layanan profesional, dan solusi pengadaan yang efisien. Kami siap mendukung kesuksesan bisnis Anda dengan produk lengkap dan layanan terbaik.',


    // footer
    'footer_description' => 'PT. Karya Pilar Nusantara adalah perusahaan terpercaya yang berfokus pada pengadaan berbagai kebutuhan instansi dan dunia usaha. Kami berkomitmmen memberikan produk berkualitas, layanan profesional, dan solusi pengadaan yang efisien. Kami siap mendukung kesuksesan bisnis Anda dengan produk lengkap dan layanan terbaik.',

]) ?>