<?= view('v2/template/about_us_template_v2', [
    // meta
    'lang' => 'cn',
    'robot_index' => 'noindex',
    'meta_title' => '关于我们',
    'meta_description' => '您值得信赖的采购合作伙伴，满足从体育用品到优质基础设施的广泛需求',
    'meta_keyword' => '关于KPN, PT Karya Pilar Nusantara, PT KPN, KPN Sidoarjo, HDPE制造商, XPE制造商, TPE制造商, 儿童玩具制造商, 定制品牌',


    // navbar & link
    'homepage_link' => '/cn',
    'homepage_link_title' => '首页',
    'product_link' => '/cn/product',
    'product_link_title' => '产品',
    'about_us_link' => '/cn/about-us',
    'about_us_link_title' => '关于我们',
    'about_us_2_link_title' => '关于',
    'contact_us_link' => '/cn/contact-us',
    'contact_us_link_title' => '联系我们',
    'contact_us_2_link_title' => '联系',
    'gallery_link' => '/cn/galeri',
    'gallery_link_title' => '画廊',
    'title' => '联系我们',

    // content
    'hero_top_title' => '关于我们',
    'hero_sub_title' => '您值得信赖的采购合作伙伴，满足从体育用品到优质基础设施的多样化需求。',
    'hero_button_title' => '联系我们',
    'about_us_top_title' => '作为您的',
    'about_us_bottom_title' => '采购解决方案',
    'about_us_description' => '我们是社区和机构在采购各类产品方面值得信赖的合作伙伴，涵盖体育用品、露营装备、儿童教育玩具以及大规模基础设施产品。我们专注于为公共和私营部门提供高效可靠的采购服务。凭借知名制造商的支持和对市场需求的深入了解，我们是每个采购项目的首选。',
    'map_top_title' => '覆盖印尼每个',
    'map_bottom_title' => '城市',
    'map_description' => '我们遍布全国，确保即使是最偏远城市也能快速送达并提供卓越服务。',
    'achievement_1' => '我们与机构和政府机关合作，专业支持他们的活动和采购需求。',
    'achievement_2' => '我们已处理超过 40,000 项来自各类机构的采购请求，服务快速、准确、可靠。',
    'achievement_2_sub_title' => '已完成请求',
    'achievement_3' => '提供超过 200 种精选产品，满足政府机构、私营企业和其他国家组织的采购需求。',
    'achievement_3_sub_title' => '产品种类',
    'value_1_top_title' => '成长的基础',
    'value_1_bottom_title' => '愿景、使命与价值观',
    'value_2_top_title' => '我们成长的基石',
    'value_2_bottom_title' => '公司愿景、使命与价值观',
    'vision_title' => '愿景',
    'vision_description' => '成为印尼领先的企业，持续创新并致力于为儿童玩具、体育及基础设施领域提供高质量产品，注重安全、耐用性与客户满意度。',
    'mission_title' => '使命',
    'mission_description' => '我们致力于提供高品质、安全、环保的产品，提供品牌定制服务，价格具有竞争力，服务专业，分销广泛，并采用现代技术推动创新与可持续发展。',
    'value_title' => '价值观',
    'value_description' => '我们相信，长期的成功建立在坚实的价值观之上。这些是我们在每一步中坚持的原则。',
    'value_1_title' => '质量优先',
    'value_1_description' => '我们提供高标准产品，以确保安全、耐用与舒适。',
    'value_2_title' => '强大协作',
    'value_2_description' => '我们与客户、内部团队和战略合作伙伴建立长期合作关系，共同成长。',
    'value_3_title' => '持续创新',
    'value_3_description' => '我们不断通过技术和设计创新，提供贴近需求、现代化和可持续的解决方案。',
    'value_4_title' => '环保可持续',
    'value_4_description' => '我们关爱环境，并通过负责任的经营实践减少负面影响。',
    'value_5_title' => '诚信与道德',
    'value_5_description' => '我们在所有业务活动中坚持诚实、透明和道德规范。',
    'value_6_title' => '灵活应变',
    'value_6_description' => '我们对市场变化保持敏感，并随时准备转型以应对未来挑战。',
    'value_7_title' => '客户至上',
    'value_7_description' => '我们倾听客户需求，把客户放在每项决策和产品开发的核心。',
    'value_8_title' => '卓越运营',
    'value_8_description' => '我们持续优化流程与工作系统，以高效一致地交付最佳成果。',
    'legality_top_title' => '我们是',
    'legality_bottom_title' => '合法注册企业',
    'company_info_title' => '公司信息',
    'company_name_title' => '企业名称：',
    'company_id_title' => '营业执照编号 (NIB)：',
    'company_type_title' => '企业类型：',
    'company_contact_title' => '联系方式与地址',
    'company_address_title' => '地址：',
    'company_email_title' => '邮箱：',
    'company_phone_title' => '电话：',
    'company_license_top_title' => '许可与',
    'company_license_bottom_title' => '经营范围',
    'company_license_sub_title' => '我们依法经营，并根据以下 KBLI 分类在 OSS 系统中注册。',
    'company_kbli_code_title' => 'KBLI 编码',
    'company_kbli_sector_title' => '行业名称',
    'company_kbli_1_sector_title' => '机械、设备及其他用品批发',
    'company_kbli_2_sector_title' => '其他家庭用品批发（未另分类）',
    'company_kbli_3_sector_title' => '其他纺织品批发',
    'company_kbli_4_sector_title' => '玩具与儿童游戏用品批发',
    'company_kbli_5_sector_title' => '金属建材批发',
    'company_kbli_6_sector_title' => '各类商品批发',
    'company_kbli_7_sector_title' => '体育用品批发',
    'company_kbli_8_sector_title' => '家用设备与用品批发',
    'company_kbli_9_sector_title' => '其他建材批发',
    'cta_banner_text' => '需要更多信息或希望合作？我们随时为您服务。',
    'cta_banner_button_title' => '联系我们',


    // footer
    'footer_description' => 'PT. Karya Pilar Nusantara 是一家专注于为机构和企业提供采购服务的值得信赖的公司。我们致力于提供优质产品、专业服务和高效的采购解决方案。我们已准备好通过完善的产品和最佳的服务支持您的业务成功。',
    'footer_company_title' => '公司简介',
]) ?>